#!/usr/bin/env python3
"""Synchronize native documentation and export the GitHub wiki (stdlib only)."""

import argparse
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
REPO = "https://github.com/TheNINJALLO/endstone-paradox"
LINK = re.compile(r"(!?\[[^\]\n]*\]\()([^\s)]+)([^)]*\))")
MIRRORS = {
    "native/BUILDING.md": "building.md",
    "native/MIGRATION.md": "migration.md",
    "native/MODULE_AUDIT.md": "module-audit.md",
    "native/VALIDATION.md": "validation.md",
    "native/RELEASE_NOTES.md": "release-notes.md",
}
PAGES = [
    ("Introduction", "documentation.md"),
    ("Getting started", "gettingstarted.md"),
    ("Release notes", "release-notes.md"),
    ("Migration and API limits", "migration.md"),
    ("Configuration", "configuration.md"),
    ("Security and clearance", "security.md"),
    ("Enforcement and lag", "violation-engine.md"),
    ("In-game GUI", "gui.md"),
    ("Web interface", "webui.md"),
    ("Global database", "global-database.md"),
    ("Evidence and integrations", "intelligence-network.md"),
    ("Moderation commands", "commands/moderation.md"),
    ("Utility commands", "commands/utility.md"),
    ("Module controls", "commands/toggles.md"),
    ("Evidence commands", "commands/violation.md"),
    ("Module overview", "modules/overview.md"),
    ("Full module audit", "module-audit.md"),
    ("Validation record", "validation.md"),
    ("Architecture", "architecture.md"),
    ("Build and test", "building.md"),
    ("FAQ", "faq.md"),
    ("Release status", "roadmap.md"),
    ("Documentation maintenance", "maintenance.md"),
]


def read(path):
    return path.read_text(encoding="utf-8")


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def without_fences(content):
    return re.sub(r"^```[^\n]*\n.*?^```[^\n]*$", "", content, flags=re.M | re.S)


def local_target(source, href):
    parsed = urlsplit(href)
    if parsed.scheme or parsed.netloc or href.startswith("#"):
        return None
    base = DOCS if parsed.path.startswith("/") and source.is_relative_to(DOCS) else source.parent
    return (base / unquote(parsed.path).lstrip("/")).resolve(), parsed.fragment


def repo_url(path):
    return REPO + ("/tree/main/" if path.is_dir() else "/blob/main/") + path.relative_to(ROOT).as_posix()


def source_links(content, source):
    def replace(match):
        target = local_target(source, match[2])
        if target is None:
            return match[0]
        path, fragment = target
        relative = path.relative_to(ROOT).as_posix()
        href = MIRRORS.get(relative, repo_url(path))
        if fragment:
            href += "#" + fragment
        return match[1] + href + match[3]

    return LINK.sub(replace, content)


def generate():
    registry = re.findall(r'\{"([a-z]+)", "([a-z]+)", (true|false)\}', read(ROOT / "native/src/engine.cpp"))
    audit = re.findall(r"^\| ([a-z]+) \| (On|Off) \| (.+) \|$", read(ROOT / "native/MODULE_AUDIT.md"), re.M)
    defaults = {name: state == "true" for name, _, state in registry}
    reviewed = {name: state == "On" for name, state, _ in audit}
    if len(defaults) != len(registry) or defaults != reviewed or len(audit) != len(registry):
        raise ValueError("Module audit IDs/defaults do not match the native registry")
    version_match = re.search(r"project\([^\n]*VERSION\s+([0-9.]+)", read(ROOT / "CMakeLists.txt"))
    if not version_match:
        raise ValueError("Cannot read the native project version")
    version = version_match[1]
    generated = {}
    for source, target in MIRRORS.items():
        body = source_links(read(ROOT / source), ROOT / source)
        if target == "release-notes.md":
            body = f"# Release notes: {version}\n\n" + body
        generated[target] = body
    descriptions = {name: description for name, _, description in audit}
    # Avoid leading comments: Docsify search indexes them as an untitled section.
    header = ""
    overview = header + f"# All {len(registry)} native modules\n\n"
    overview += (f"These are the Paradox {version} defaults for a new installation. Persisted settings take precedence. "
                 "Modules include observations, validation, policies and utilities; enabling a module does not imply it can punish a player. "
                 "Review [enforcement and lag recovery](../violation-engine.md), [module controls](../commands/toggles.md) "
                 "and [migration limits](../migration.md).\n\n"
                 "| Module | Kind | Default | Native behavior |\n| --- | --- | --- | --- |\n")
    sidebar = "<!-- Generated by native/tools/sync-docs.py. -->\n\n"
    sidebar += "\n".join(f"- [{title}](/{href})" for title, href in PAGES) + "\n- **Modules by kind**\n"
    for kind in dict.fromkeys(kind for _, kind, _ in registry):
        sidebar += f"  - **{kind.capitalize()}**\n"
        for name, module_kind, state in registry:
            if kind == module_kind:
                sidebar += f"    - [{name}](/modules/{name}.md)\n"
    generated["_sidebar.md"] = sidebar
    for name, kind, state in registry:
        default = "On" if state == "true" else "Off"
        description = descriptions[name]
        overview += f"| [{name}]({name}.md) | {kind} | {default} | {description} |\n"
        generated[f"modules/{name}.md"] = (
            header + f"# {name}\n\nParadox Native {version} | **{kind.capitalize()}** | New-install default: **{default}**\n\n"
            f"## Native behavior\n\n{description}\n\n"
            "## Controls\n\n"
            f"Use `/ac-modstate {name} on` or `/ac-modstate {name} off`. The generic module handler requires clearance 3 "
            "or `paradox.modules`, plus clearance 4 or `paradox.settings` to change state. Operators have these permissions by default. "
            "Changes persist to SQLite and override TOML defaults. "
            "For utility commands and special cases, see [module controls](../commands/toggles.md) and [player utilities](../commands/utility.md).\n\n"
            "## Evidence and limits\n\n"
            "Observations never escalate into punishment, including in hard mode. Administrative policies are separate from cheating findings. "
            "Read the [lag and enforcement guide](../violation-engine.md) and [full module audit](../module-audit.md) "
            "before changing policy. The [validation record](../validation.md) distinguishes automated coverage from "
            "gameplay still needing local acceptance.\n\n[All modules](overview.md)\n"
        )
    generated["modules/overview.md"] = overview
    for name in ("documentation.md", "gettingstarted.md", "cover.md"):
        if f"Native {version}" not in read(DOCS / name):
            raise ValueError(f"{name} does not identify current native version {version}")
    return generated, registry


def check_links(paths):
    errors = []
    count = 0
    for path in paths:
        for match in LINK.finditer(without_fences(read(path))):
            target = local_target(path, match[2])
            if target is None:
                continue
            count += 1
            if not target[0].exists():
                errors.append(f"{path.relative_to(ROOT)}: missing link {match[2]}")
    if errors:
        raise ValueError("\n".join(errors))
    return count


def check_commands(registry):
    source = read(ROOT / "native/src/plugin.cpp")
    registered = {name for name, _, _ in registry}
    for group in ("admin", "utility"):
        match = re.search(r"const std::vector<std::string> " + group + r" = \{(.*?)\};", source, re.S)
        if not match:
            raise ValueError(f"Cannot read {group} command registry")
        registered.update(re.findall(r'"([a-z-]+)"', match[1]))
    errors = []
    documented = set()
    for path in DOCS.rglob("*.md"):
        for name in re.findall(r"\bac-([a-z]+(?:-[a-z]+)*)\b", read(path)):
            if name not in registered:
                errors.append(f"{path.relative_to(ROOT)}: unregistered command ac-{name}")
            documented.add(name)
    # Module commands can use the generic toggle form; require every other registered command.
    missing = registered - documented - {name for name, _, _ in registry}
    if missing:
        errors.append(f"Undocumented commands: {sorted(missing)}")
    if errors:
        raise ValueError("\n".join(errors))


def wiki_name(path):
    rel = path.relative_to(DOCS)
    if rel.as_posix() == "documentation.md":
        return "Home"
    return "-".join(part.capitalize() for part in rel.with_suffix("").parts)


def export_wiki(output):
    output = output.resolve()
    if output == ROOT or output == DOCS or ROOT.is_relative_to(output) or output.is_relative_to(DOCS):
        raise ValueError("Wiki output must be a separate directory, such as scratch/paradox-wiki")
    paths = [DOCS / href for _, href in PAGES] + sorted((DOCS / "modules").glob("*.md"))
    names = {p.resolve(): wiki_name(p) for p in paths}
    if len(set(names.values())) != len(names):
        raise ValueError("Wiki page names collide")

    def translate(content, source):
        def replace(match):
            target = local_target(source, match[2])
            if target is None:
                return match[0]
            path, fragment = target
            href = REPO + "/wiki/" + names[path] if path in names else repo_url(path)
            if fragment:
                href += "#" + fragment
            return match[1] + href + match[3]
        return LINK.sub(replace, content)

    for path, name in names.items():
        content = re.sub(r"\A<!--.*?-->\s*", "", read(path), flags=re.S)
        write(output / (name + ".md"), translate(content, path))
    write(output / "_Sidebar.md", translate(read(DOCS / "_sidebar.md"), DOCS / "_sidebar.md"))
    write(output / "_Footer.md", "Maintained from [the documentation source](" + REPO + "/tree/main/docs). "
          "[Documentation site](https://theninjallo.github.io/endstone-paradox/) | "
          "[Stable release](" + REPO + "/releases/latest).\n")
    print(f"Exported {len(names)} wiki pages plus sidebar/footer to {output}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated docs differ; do not change them")
    parser.add_argument("--wiki-output", type=Path, help="Export all current guides as GitHub wiki Markdown")
    args = parser.parse_args()
    generated, registry = generate()
    stale = []
    for name, content in generated.items():
        path = DOCS / name
        if args.check:
            if not path.exists() or read(path) != content:
                stale.append(name)
        else:
            write(path, content)
    if stale:
        raise ValueError("Run python native/tools/sync-docs.py to update: " + ", ".join(stale))
    active = list(DOCS.rglob("*.md")) + [ROOT / "README.md"] + list((ROOT / "native").glob("*.md"))
    links = check_links(active)
    check_commands(registry)
    print(f"Documentation checks passed: {len(registry)} modules, {len(generated)} generated files, {links} local links")
    if args.wiki_output:
        export_wiki(args.wiki_output)


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
